### ISSUE TITLE
Doing the reverse: VGA to Mac SE video

### ISSUE THREAD

**Issue by jmacato** [guruthree/mac-se-video-converter#2]
Hey @guruthree, this is quite the exciting project! I do wonder though if it's possible to do the reverse, to make VGA input drive the mac se's CRT display?

**Comment by guruthree** [comment]
Thanks! I think it should be possible to do VGA to compact Mac CRT, but there are a couple challenges I see:

- VGA is an analogue signal at 0.7 V. Even if we ignore colour so we can pretend it's digital, it's still digital 0 to 0.7 V. This would need to be boosted to 3.3 V for reading into the PICO. This might be posible with another logic level converter, but it'd still need some extra circuitry for a 0.7 V reference voltage. (It shouldn't be a problem to pretend it's digital, the Mac's circuitry is all for black and white anyway.)
- Resolution. I don't know how flexible the CRT circuitry is. 512x342 isn't a great match with VGA, but maybe the analogue board would be happy to accept 512x384, which is more standard. It'd be best if it would accept 640x480, but I've only heard of that working with a Compact Colour Mac CRT. Someone would have to do some testing, and with testing there's no guarantee nothing would go wrong.
- Resolution part 2, memory boogaloo. If the goal would be to take in something like 1024x768 and rescale it to 512x342 (or 640x480) memory might be an issue, either not enough or not fast enough.
- Resolution part 3, the return of the timings. At 640x480 (i.e., VGA) the pixel clock is around 25 MHz or 60% higher than it was reading in the Mac's video. As resolution goes up pixel clock gets higher and consequently harder to read.

**Comment by jmacato** [comment]
Thanks for the quick reply! 

WRT Resolution part 1: Sadly i dont think it's quite tolerant of out-of-spec signals as far as my testing has gone.. I was thinking of just "faking" a VGA resolution and perhaps just cutting off the extra pixels. But then again that might not sit well with other folks (personally i'll be fine with it haha).

**Comment by guruthree** [comment]
Annoying that the analgoue board circuitry isn't too flexible, but I'm also not surprised considering it's driven by TTL logic (as opposed to an analogue signal). I think there might be some free space in the vertical blank that could be used to eke out a bit more vertical resolution and get closer to 4:3 (512xz384) though. 

Chopping off part of the frame to go from 640x480 to 512x342 should be a pretty easy manipulation for the pico to do. Something like emulator output could be made to run in just the visible portion of the screen and show up perfectly. Although for that specific use case it would probably be easier to get the emulator to dump its framebuffer over USB serial to the Pico for it to drive the CRT than to go through the extra steps of VGA capture. The more specific the application the more steps can be saved!

**Comment by jmacato** [comment]
> Annoying that the analgoue board circuitry isn't too flexible, but I'm also not surprised considering it's driven by TTL logic (as opposed to an analogue signal). I think there might be some free space in the vertical blank that could be used to eke out a bit more vertical resolution and get closer to 4:3 (512xz384) though.

Yeah sadly it's quite sensitive when it comes to signal spec, i was a little too far off with my RPi4 DPI settings and it fried the board after a while.

I saw this project on 68kmla but im not sure about the inductance/spec of the flyback bypass he did there: https://68kmla.org/bb/index.php?threads/compact-mac-retina-display.2847/page-4#post-409397

> Chopping off part of the frame to go from 640x480 to 512x342 should be a pretty easy manipulation for the pico to do. 

Yeah, although what i have in mind is to allow at least 640x480 input from arbitrary source, so that folks could use any device for the CRT but the emulator idea is quite interesting as well :D
