### ISSUE TITLE
Not quite working correctly with my Mac Plus.

### ISSUE THREAD

**Issue by TimRustige** [guruthree/mac-se-video-converter#5]
Hi, I built the circuit and it sort of works, but I have what looks like noise, see attached photo
![IMG_20241112_155520](https://github.com/user-attachments/assets/baae78e8-ba24-44d5-9b20-216eaef4703e)

Things I've tried to fix this issue:
Tried a Pi Zero and a Pi Zero W
Tried two different VGA screens - both the same, one is a really good multi sync Eizo L367
Tried a breadboard version and PCB I made - so different level shifter boards but same design
Tried adding a diode to the 5v line from the Mac Plus that's powering the Pi Pico

I've not tried removing the level shifters yet. I can't see level shifters on the design at JCM-1.com
or the links to the working examples?

I'm not using the Pimoroni board. I'm using the 3 resistors to a VGA port from a Pico Mac design here:
https://github.com/evansm7/pico-mac

From what I read, different software values might be required for Mac Plus compared to SE?

**Comment by TimRustige** [comment]
also, a weird thing. If the floppy drive is connected, the system detects a floppy that needs formatting, even though the floppy drive is empty

**Comment by TimRustige** [comment]
Please ignore. Set the NOP to 22 , works great now.
![IMG_20241112_193158](https://github.com/user-attachments/assets/991f6620-2ea8-4b01-80ea-254394af243a)
![Uploading IMG_20241112_193153.jpg…]()

**Comment by guruthree** [comment]
Great that you've got it working! I've updated the troubleshooting to link to this issue and included your description of 'noisy' to help anyone else track down the same problem.
